import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from "react";
import Link from "next/link";

export class UserForm extends React.Component {

  constructor(props) {
    super(props);
    this.state = {value: ''};
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }
  handleChange(event) {
    this.setState({value: event.target.value});
  }
  handleSubmit(event) {
    event.preventDefault();
  }

  render() {
    return (
        <>
<<<<<<< HEAD
=======
            <Head>
                <title>Github Profile Card</title>
                <meta name="description" content="Traact Internship Project" />
                <link rel="icon" href="/home/labiot/WebstormProjects/GitHubPCex/public/favicon.ico" />
            </Head>
>>>>>>> 7689708 (commit)
            <form onSubmit={this.handleSubmit}>
                <label>
                    <input type="text" value={this.state.value} onChange={this.handleChange} />
                </label>
            </form>
            <Link href={this.state.value}>
                <h4>CLICK ME to go to {this.state.value} page</h4>
            </Link>
        </>
<<<<<<< HEAD
=======

>>>>>>> 7689708 (commit)

    );
  }
}

export default function Home() {

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Get GitHub Profile Cards!
          </h1>
          <UserForm></UserForm>

        </main>

        <footer className={styles.footer}>

        </footer>
      </div>
  )
}